import type { Config } from 'tailwindcss';
import { nextui } from '@nextui-org/react';

const config: Config = {
    content: [
        './app/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './app/components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                display: ['Space Grotesk', 'Inter', 'system-ui', 'sans-serif'],
            },
        },
    },

    darkMode: 'class',
    plugins: [
        nextui({
            themes: {
                light: {
                    colors: {
                        default: {
                            '50': '#fafafa',
                            '100': '#f2f2f3',
                            '200': '#ebebec',
                            '300': '#e3e3e6',
                            '400': '#dcdcdf',
                            '500': '#d4d4d8',
                            '600': '#afafb2',
                            '700': '#8a8a8c',
                            '800': '#656567',
                            '900': '#404041',
                            foreground: '#000',
                            DEFAULT: '#d4d4d8',
                        },
                        primary: {
                            '50': '#e6ebf0',
                            '100': '#c2cedc',
                            '200': '#9eb1c7',
                            '300': '#7a94b2',
                            '400': '#57789e',
                            '500': '#335b89',
                            '600': '#2a4b71',
                            '700': '#213b59',
                            '800': '#182b41',
                            '900': '#0f1b29',
                            foreground: '#fff',
                            DEFAULT: '#335b89',
                        },
                        secondary: {
                            '50': '#f0eaf6',
                            '100': '#dacde8',
                            '200': '#c5afdb',
                            '300': '#b092ce',
                            '400': '#9a74c0',
                            '500': '#8557b3',
                            '600': '#6e4894',
                            '700': '#563974',
                            '800': '#3f2955',
                            '900': '#281a36',
                            foreground: '#fff',
                            DEFAULT: '#8557b3',
                        },
                        success: {
                            '50': '#e7f7ee',
                            '100': '#c5ecd6',
                            '200': '#a4e2be',
                            '300': '#82d7a7',
                            '400': '#61cc8f',
                            '500': '#3fc177',
                            '600': '#349f62',
                            '700': '#297d4d',
                            '800': '#1e5c39',
                            '900': '#133a24',
                            foreground: '#000',
                            DEFAULT: '#3fc177',
                        },
                        warning: {
                            '50': '#fef6ea',
                            '100': '#fceace',
                            '200': '#fadeb1',
                            '300': '#f8d294',
                            '400': '#f6c577',
                            '500': '#f4b95a',
                            '600': '#c9994a',
                            '700': '#9f783b',
                            '800': '#74582b',
                            '900': '#49381b',
                            foreground: '#000',
                            DEFAULT: '#f4b95a',
                        },
                        danger: {
                            '50': '#f9e5ec',
                            '100': '#f0c2d2',
                            '200': '#e79eb7',
                            '300': '#df7a9d',
                            '400': '#d65682',
                            '500': '#cd3268',
                            '600': '#a92956',
                            '700': '#852144',
                            '800': '#611831',
                            '900': '#3e0f1f',
                            foreground: '#fff',
                            DEFAULT: '#cd3268',
                        },
                        background: '#ffffff',
                        foreground: '#000000',
                        content1: {
                            DEFAULT: '#ffffff',
                            foreground: '#000',
                        },
                        content2: {
                            DEFAULT: '#f4f4f5',
                            foreground: '#000',
                        },
                        content3: {
                            DEFAULT: '#e4e4e7',
                            foreground: '#000',
                        },
                        content4: {
                            DEFAULT: '#d4d4d8',
                            foreground: '#000',
                        },
                        focus: '#006FEE',
                        overlay: '#ffffff',
                    },
                },
                dark: {
                    colors: {
                        default: {
                            '50': '#0b0b0c',
                            '100': '#161619',
                            '200': '#222225',
                            '300': '#2d2d32',
                            '400': '#38383e',
                            '500': '#606065',
                            '600': '#88888b',
                            '700': '#afafb2',
                            '800': '#d7d7d8',
                            '900': '#ffffff',
                            foreground: '#fff',
                            DEFAULT: '#38383e',
                        },
                        primary: {
                            '50': '#0f1b29',
                            '100': '#182b41',
                            '200': '#213b59',
                            '300': '#2a4b71',
                            '400': '#335b89',
                            '500': '#57789e',
                            '600': '#7a94b2',
                            '700': '#9eb1c7',
                            '800': '#c2cedc',
                            '900': '#e6ebf0',
                            foreground: '#fff',
                            DEFAULT: '#335b89',
                        },
                        secondary: {
                            '50': '#281a36',
                            '100': '#3f2955',
                            '200': '#563974',
                            '300': '#6e4894',
                            '400': '#8557b3',
                            '500': '#9a74c0',
                            '600': '#b092ce',
                            '700': '#c5afdb',
                            '800': '#dacde8',
                            '900': '#f0eaf6',
                            foreground: '#fff',
                            DEFAULT: '#8557b3',
                        },
                        success: {
                            '50': '#133a24',
                            '100': '#1e5c39',
                            '200': '#297d4d',
                            '300': '#349f62',
                            '400': '#3fc177',
                            '500': '#61cc8f',
                            '600': '#82d7a7',
                            '700': '#a4e2be',
                            '800': '#c5ecd6',
                            '900': '#e7f7ee',
                            foreground: '#000',
                            DEFAULT: '#3fc177',
                        },
                        warning: {
                            '50': '#49381b',
                            '100': '#74582b',
                            '200': '#9f783b',
                            '300': '#c9994a',
                            '400': '#f4b95a',
                            '500': '#f6c577',
                            '600': '#f8d294',
                            '700': '#fadeb1',
                            '800': '#fceace',
                            '900': '#fef6ea',
                            foreground: '#000',
                            DEFAULT: '#f4b95a',
                        },
                        danger: {
                            '50': '#3e0f1f',
                            '100': '#611831',
                            '200': '#852144',
                            '300': '#a92956',
                            '400': '#cd3268',
                            '500': '#d65682',
                            '600': '#df7a9d',
                            '700': '#e79eb7',
                            '800': '#f0c2d2',
                            '900': '#f9e5ec',
                            foreground: '#fff',
                            DEFAULT: '#cd3268',
                        },
                        background: '#000000',
                        foreground: '#ffffff',
                        content1: {
                            DEFAULT: '#18181b',
                            foreground: '#fff',
                        },
                        content2: {
                            DEFAULT: '#27272a',
                            foreground: '#fff',
                        },
                        content3: {
                            DEFAULT: '#3f3f46',
                            foreground: '#fff',
                        },
                        content4: {
                            DEFAULT: '#52525b',
                            foreground: '#fff',
                        },
                        focus: '#006FEE',
                        overlay: '#000000',
                    },
                },
            },
            layout: {
                disabledOpacity: '0.5',
            },
        }),
    ],
};
export default config;
