import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import NavigationBar from '@/components/navbar/NavigationBar';
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={inter.className}>
                <Providers>
                    <NavigationBar />
                    <div className="flex h-[calc(100vh-64px-40px)] flex-col items-center">{children}</div>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
